### ISSUE TITLE
Upgrade management

### ISSUE THREAD

**Issue by Arkanosis** [REGOVAR/Regovar#42]
(For after the first production deployment.)

After upgrading the code of Regovar, there must be a version check to ensure that the database schema and the code are still compatible with each other. If not, there must be either an auto-upgrade of the database (and its content) or (if it can take a while) a mandatory manual intervention before restart (in this case, the admin must have been asked for first, as unexpected downtime is to be avoided).

**Comment by ikit** [comment]
Do you know if it's possible for git to "emit" a warning when a commit is done on a specific file ? It could be usefull to warn/remind developper to don't forger to increment db version when they modify the db schema (install/create_all.sql)

**Comment by Arkanosis** [comment]
Sure, with a [pre-commit hook](https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks). That said, client-side hooks must be installed by each developer individually; they aren't cloned with the sources.
