### ISSUE TITLE
Sort on filter column

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/Regovar#44]
```
sudo -u regovar psql -d regovar -c "DROP TABLE IF EXISTS wt_7_tmp CASCADE; CREATE TABLE wt_7_tmp AS SELECT ROW_NUMBER() OVER(ORDER BY s89_filter) as page, variant_id, array_remove(array_agg(trx_pk_value), NULL) as trx, count(trx_pk_value) as trx_count, s89_filter FROM wt_7 WHERE (is_denovo=false AND is_rec_hom=true) GROUP BY variant_id, s89_filter"
ERREUR:  n'a pas pu identifier un opérateur d'égalité pour le type json
LIGNE 1 : ...o=false AND is_rec_hom=true) GROUP BY variant_id, s89_filter
```

**Comment by Arkanosis** [comment]
`s89_filter` is a JSON column, so it can't be compared (and therefore one can't `ORDER BY` it nor `GROUP BY` it).

The `#>>` operator can be used to convert it to text, and the `'{}'` operand can be used to convert it all.

Using `OVER(ORDER BY s89_filter #>> '{}')` … `SELECT` … `s89_filter #>> '{}'` … `GROUP BY variant_id, s89_filter #>> '{}'` works. Dunno if that's what we actually want, but…
