### ISSUE TITLE
Create a new request "maybe de novo (vcf)" because of missing information about coverage

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/Regovar#47]
``` diff
diff --git a/regovar/core/managers/filter_manager.py b/regovar/core/managers/filter_manager.py
index 3abed23..e01b2ac 100644
--- a/regovar/core/managers/filter_manager.py
+++ b/regovar/core/managers/filter_manager.py
@@ -492,7 +492,8 @@ class FilterEngine:
         # Recessif Homozygous
         query += "is_rec_hom=(s{1}_gt=1), "
         # Inherited and denovo
-        query += "is_denovo=(s{1}_gt>0 AND s{2}_gt=0 AND s{3}_gt=0), "
+        query += "is_denovo_gvcf=(s{1}_gt>0 AND s{2}_gt=0 AND s{3}_gt=0), "
+        query += "maybe_denovo_vcf=(s{1}_gt>0 AND COALESCE(s{2}_gt,0)=0 AND COALESCE(s{3}_gt,0)=0), "
         # Autosomal
         query += "is_aut=(chr<23), "
         # X-Linked
```
But, THIS is not the proper algorithm to determine whether a variant is *de novo* or not (for example if there is another alt in one of the parents).

And rename the "*de novo*" quick filter into "*de novo* (gvcf)".

**Comment by ikit** [comment]
The test is done for all chr-pos-ref-alt existing in the analysis, so if the parent have another alt, this alt will also be tested.

**Comment by ikit** [comment]
Do you really need both ? as Maybe_denovo will contains is_denovo results ? It may be more intuitive for user to just display "maybe_denovo" as "denovo", then they will see in the GT column if the parent allele exists or not

**Comment by Oodnadatta** [comment]
What do you mean in your first comment?
> The test is done for all chr-pos-ref-alt existing in the analysis, so if the parent have another alt, this alt will also be tested.

Your comment is relevant. So, for now, we just keep one "de novo" filter and we add an information tooltip with explanations about this, for example, with a little 'i' next to it saying when your click on it: 
In French, "Les variants "*de novo*" obtenus avec ce filtre contiennent également les locus non couverts chez les parents" and in English "The remaining "*de novo*" variants also include uncovered locus in the parents.*

But this is not the proper algorithm yet to determine whether a variant is *de novo* or not (for example if there is another alt in one of the parents). I create another issue precisely for this.
