### ISSUE TITLE
Improve de novo query to take into account alternative variants in parents

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/Regovar#48]

**Comment by ikit** [comment]
In my opinion, these variants are already covered by the current algorythm, can you please add more details to the issue ?

**Comment by Oodnadatta** [comment]
For example:
- reference: C/C
- child: C/A
- mother: C/T
- father: C/G

**Comment by ikit** [comment]
this variant will create the following entry in the database

| ref | alt | gt_child | gt_mother | gt_father |
| --- | --- | --- | --- | --- |
| C | C | 2 | 2 | 2 |
| C | A | 2 | -1 | -1 |
| C | T | -1 | 2 | -1 |
| C | G | -1 | -1 | 2 |

GT map reminder:

- NULL: unknow (entry not in VCF)
- -1 : don't have this allele (gvcf)
- 0 : ref/ref : the sample is ref/ref with this allele entry
- 1 : alt/alt : the sample is alt/alt with this allele entry (= this alt)
- 2 : ref/alt : the sample is ref/alt with this allele entry (= this alt)
- 3 : alt1/alt2 : the sample is alt1/alt1 with this allele entry (= this alt) and another alt (another entry)

So to retrieve all denovo the test shall be: `SELECT * WHERE gt_child >0 AND COALESCE(gt_mother,0) <=0 AND COALESCE(gt_father, 0) <= 0`

Are you agree ?

**Comment by ikit** [comment]
By looking in a vcf, I have the following entry :
```
chr1    69761   .   A   T   65.15   LowQuality;VQSRTrancheSNP99.00to99.90   ... GT:AD:DP:GQ:PL  ./.:2,0:2:.:0,0,0   0/0:2,0:2:6:0,6,71  0/1:2,3:5:44:93,0,44
```

That create the following entries in the DB:
```
sql regovar "select vcf_line, chr, pos, ref, alt, s1_gt, s2_gt, s3_gt from wt_1 order by vcf_line"
 vcf_line | chr |  pos   | ref | alt | s1_gt | s2_gt | s3_gt
----------+-----+--------+-----+-----+-------+-------+-------
       97 |   1 |  69760 | A   | A   |    -1 |     0 |     2
       97 |   1 |  69760 | A   | T   |    -1 |    -1 |     2
```
Does it seem correct for you ?
I'm not sure about how should be interpreted the ./. in the vcf, does it means that we don't know if the sample have the variant, or we are sure that it doesn't have ?
