### ISSUE TITLE
About information tooltips

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/Regovar#49]
- What does "composite variant" mean?
https://github.com/REGOVAR/Regovar/blob/b74b9cd685dc74a56a35815717c847be3b9d424f/install/create_all.sql#L657
- Where is the information displayed? In the **filter** tooltip? In the **column** tooltip?

**Comment by ikit** [comment]
You can display this column (select it in the Regovar database in the annotation panel) or filter on it via quickfilter or advanced filter

This information is computed just [after the import of a vcf file](https://github.com/REGOVAR/Regovar/blob/master/regovar/core/managers/imports/vcf_manager.py#L667)

Then this information is used when you create an [analysis that is not a trio](https://github.com/REGOVAR/Regovar/blob/master/regovar/core/managers/filter_manager.py#L463). 
(compound htz for trio is computed [here](https://github.com/REGOVAR/Regovar/blob/master/regovar/core/managers/filter_manager.py#L506))

**Comment by Oodnadatta** [comment]
Thank you!
Then, for note, composite variants are variants that are at least two in the same gene, whichever the parental inheritance.
