### ISSUE TITLE
Exonic filter is incorrect

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/Regovar#52]
Exonic filter must depend on genomic regions and not on variant consequences. These are two different concepts.

![image](https://user-images.githubusercontent.com/5510283/36344843-80698fe0-1420-11e8-876b-627415c6eb6f.png)

![image](https://user-images.githubusercontent.com/5510283/36344834-52d9eaac-1420-11e8-9663-6c39a53aec27.png)

**Comment by ikit** [comment]
Does VEP provide me this information ?

Could it be something like : ` Consequence  != intron_variant AND Consequence != intergenic_variant`

**Comment by Oodnadatta** [comment]
RefSeq provide this information. We have to use it.

We already have this information in the database, but here is how to obtain it with the GUI using [UCSC table browser](http://genome.ucsc.edu/cgi-bin/hgTables).

![image](https://user-images.githubusercontent.com/5510283/36401287-d4508a70-15d6-11e8-8330-5dee9c7b8339.png)
![image](https://user-images.githubusercontent.com/5510283/36401330-27429b42-15d7-11e8-8a22-fb536147d712.png)
![image](https://user-images.githubusercontent.com/5510283/36401318-190a3df0-15d7-11e8-8ebe-0f91f960ab59.png)

**Comment by ikit** [comment]
But if we test only on txstart and txend we will also retrieve intronic variant, right?

**Comment by Oodnadatta** [comment]
Absolutely. Thank you for your relevant observation! :D
It is exonStarts and exonEnds instead of tx*.

**Comment by Oodnadatta** [comment]
Thanks!
