### ISSUE TITLE
Test rst in ReadTheDocs instead of Md to adjust the depth in the table of contents

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/Regovar#64]
To convert with pandoc
```sh
pandoc --from=markdown --to=rst --output=readme.rst readme.md
```
To test the depth of the table of contents
```rst
.. toctree::
  :maxdepth: 2
```

**Comment by ikit** [comment]
This feature is a "well know" issue, and the mkdocs team is working to fix it in the next planned version.
see [mkdocs \#699](https://github.com/mkdocs/mkdocs/issues/699)

unfortunately, there is no release date for this next version.
So, as temp solution, I propose to add all pages in the navigation bar... as I did in [my last commit](https://github.com/REGOVAR/Regovar/commit/9067402d74ce8b3e0c167374d35c1bab72a087f5) of the doc

**Comment by ikit** [comment]
As now read the doc use mkdocs >= 1.0, all the page .md are rendered even if they are not added into the nav menu. So I close this ticket as we build a site with the custom deepth level and keeping a nav menu clean and simple.
